baseurl = "http://iberianpig.github.io/"
languageCode = "ja-jp"
title = "iberianpigsty"
copyright = "Copyright (c) 2014 - 2016, iberianpigsty; all rights reserved."
paginate = 10
theme = "hugo_theme_robust"

description = "Linux, Rails, AngularJS, Androidネタを投下します。/ メインマシンはDell XPS13, elementaryOS 14.04 freya/ 2014-04よりSIerを退職，現在Web/Mobileアプリ開発の修行中。"

[params]
  disqusShortname = "your disqus id." # optional

[permalinks]
    post = "/:year/:month/:day/:filename/"


