baseurl = "https://iberianpig.github.io/"
LanguageCode = "ja-jp"
title = "iberianpigsty"
copyright = "Copyright (c) iberianpigsty; all rights reserved."
paginate = 16
theme = "hugo_theme_robust"
canonifyurls = true
publishdir = "public"
MetaDataFormat = "yaml"

[taxonomies]
tag = "tags"

[params]
twitterId = "nukumaro22"
githubId = "iberianpig"
GoogleAnalyticsUserID = "G-8G6M9151B3"
email = "yhkyky+work@gmail.com"
author = "Kohei Yamada"
aboutme = "自分が便利そうだと思ったものを作っています。Linux/Ruby/Vim が好きです。"
aboutwork = "スタートアップ企業の技術支援をしています。お仕事のご相談はメールかX(Twitter)でご連絡ください。"
description = "iberianpigの技術ブログ"
image = "https://secure.gravatar.com/avatar/0cad0568651dbea482d80104ee3bf9b3?size=500"

[params.eyecatch]
linux = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/652px-Tux.svg.png" 

[markup.goldmark.renderer]
unsafe = true

[minify]
disableXML = true
