baseurl = "https://iberianpig.github.io/"
languageCode = "ja-jp"
title = "iberianpigsty"
copyright = "Copyright (c) 2014 - 2021, iberianpigsty; all rights reserved."
paginate = 16
theme = "hugo_theme_robust"
canonifyurls = true
publishdir = "public"
MetaDataFormat = "yaml"

[taxonomies]
  tag = "tags"

[params]
    disqusShortname = "iberianpigsty"
    GoogleAnalyticsUserID = "UA-45334010-1"
    GoogleAdsenseId = "ca-pub-4578444047174224"
    twitterId = "nukumaro22"
    githubId = "iberianpig"
    email = "yhkyky+work@gmail.com"
    author = "Kohei Yamada"
    aboutme = "趣味・仕事で平日休日変わらず毎日コードを書いてます。"
    aboutwork = "フリーランスのエンジニアチームでスタートアップのお手伝い。バックエンド、フロントエンド問わず色々。バックエンド、特にRubyが得意。お仕事のご相談はお気軽に。"
    description = "iberianpigの技術ブログ"

[params.eyecatch]
    linux = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/652px-Tux.svg.png" 
[params.adsense]
    sidebar = "2886367399" 
    content = "2746766592" 

[markup.goldmark.renderer]
unsafe = true
