baseurl = "https://iberianpig.github.io/"
languageCode = "ja-jp"
title = "iberianpigsty"
copyright = "Copyright (c) 2014 - 2016, iberianpigsty; all rights reserved."
paginate = 16
theme = "hugo_theme_robust"
canonifyurls = true
publishdir = "public"
MetaDataFormat = "yaml"

[params]
    disqusShortname = "iberianpigsty"
    GoogleAnalyticsUserID = "UA-45334010-1"
    twitterId = "nukumaro22"
    author = "Kohei Yamada"
    description = "Linux, Rails, AngularJS, Androidなどについての技術ブログ。メインマシンはDell XPS13, OSはelementaryOS 14.04 freya。2014-04よりSIerを退職し、スタートアップにてWebサービス開発を行う。"

[params.eyecatch]
    linux = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/652px-Tux.svg.png" 
