baseurl = "https://iberianpig.github.io/"
languageCode = "ja-jp"
title = "iberianpigsty"
copyright = "Copyright (c) 2014 - 2016, iberianpigsty; all rights reserved."
paginate = 16
theme = "hugo_theme_robust"
canonifyurls = true
publishdir = "public"
MetaDataFormat = "yaml"

[taxonomies]
  tag = "tags"

[params]
    disqusShortname = "iberianpigsty"
    GoogleAnalyticsUserID = "UA-45334010-1"
    GoogleAdsenseId = "ca-pub-4578444047174224"
    twitterId = "nukumaro22"
    githubId = "iberianpig"
    email = "yhkyky@gmail.com"
    author = "Kohei Yamada"
    aboutme = "Sony → Wanderlust → StartupTechnology → freelance 現在フリーランスのエンジニアチーム山田㌠のリーダーとしてWeb系のスタートアップのコンサルティング、開発支援を行っています。サーバーサイド、特にRubyが得意ですが、フロントエンドもやります。"
    description = "iberianpigの技術ブログ"

[params.eyecatch]
    linux = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/652px-Tux.svg.png" 
[params.adsense]
    sidebar = "2886367399" 
    content = "2746766592" 
