baseurl = "https://iberianpig.github.io/"
languageCode = "ja-jp"
title = "iberianpigsty"
copyright = "Copyright (c) iberianpigsty; all rights reserved."
paginate = 16
theme = "hugo_theme_robust"
canonifyurls = true
publishdir = "public"
MetaDataFormat = "yaml"

[taxonomies]
  tag = "tags"

[params]
    disqusShortname = "iberianpigsty"
    GoogleAnalyticsUserID = "G-8G6M9151B3"
    twitterId = "nukumaro22"
    githubId = "iberianpig"
    email = "yhkyky+work@gmail.com"
    author = "Kohei Yamada"
    aboutme = "自分が便利そうだと思ったものを作っています。Linux/Ruby/Vim が好きです。"
    aboutwork = "チームでスタートアップ企業の技術支援をしています。Rubyが得意です。お仕事のご相談はメールかX(Twitter)でご連絡ください。"
    description = "iberianpigの技術ブログ"

[params.eyecatch]
    linux = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/652px-Tux.svg.png" 

[markup.goldmark.renderer]
unsafe = true

[minify]
disableXML = true
